name: Deploy Wiki Container to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Set up SSH key
    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

    # Step 3: Add server to known_hosts
    - name: Add server to known_hosts
      run: |
        ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

    # Step 4: Copy the Docker Compose file to the server
    - name: Copy Docker Compose to server
      run: |
        scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} ../../docker/docker-compose.yml ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/tmp/docker-compose.yml

    # Step 5: Deploy using Docker Compose on the remote server
    - name: Deploy using Docker Compose
      run: |
        ssh -t -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd /tmp
          # Stop and remove any existing containers
          sudo docker-compose down || true
          # Run the containers using Docker Compose
          sudo docker-compose up -d
        EOF
